DELETE FROM CONTAS_PAGAR;
DELETE FROM CONTAS_RECEBER;

DELETE FROM ITEM_COMPRA;
DELETE FROM ITEM_VENDA

DELETE FROM COMPRA;
DELETE FROM VENDA;

DELETE FROM PRODUTO;
DELETE FROM FORNECEDOR;
DELETE FROM CLIENTE;
DELETE FROM EMPRESA;