/* cria a procedure para diminuir o valor de venda dos produtos */
SET TERM ^ ;
CREATE PROCEDURE SP_DIMINUI_VALOR_VENDA (
    P_ID_PRODUTO Integer,
    P_PORCENTAGEM Float )
AS
BEGIN
  /* ATUALIZA O VALOR DE VENDA*/ 
  UPDATE PRODUTO
  SET PRODUTO.VL_VENDA=PRODUTO.VL_VENDA - ((PRODUTO.VL_VENDA * :P_PORCENTAGEM)/100)
  WHERE PRODUTO.ID_PRODUTO= :P_ID_PRODUTO;
END^
SET TERM ; ^

SELECT * FROM PRODUTO
WHERE ID_PRODUTO=1

EXECUTE PROCEDURE SP_AUMENTA_VALOR_VENDA_TODOS(50);

EXECUTE PROCEDURE SP_DIMINUI_VALOR_VENDA(1,50);















